trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: 'vsprojects/pcsx-redux.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
